///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace calculatorRanorexSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the calculatorRanorexSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("295d527e-382c-40e3-bbc6-8f33ede29ee8")]
    public partial class calculatorRanorexSolutionRepository : RepoGenBaseFolder
    {
        static calculatorRanorexSolutionRepository instance = new calculatorRanorexSolutionRepository();
        calculatorRanorexSolutionRepositoryFolders.ExplorerAppFolder _explorer;
        calculatorRanorexSolutionRepositoryFolders.SearchAppFolder _search;
        calculatorRanorexSolutionRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the calculatorRanorexSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("295d527e-382c-40e3-bbc6-8f33ede29ee8")]
        public static calculatorRanorexSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public calculatorRanorexSolutionRepository() 
            : base("calculatorRanorexSolutionRepository", "/", null, 0, false, "295d527e-382c-40e3-bbc6-8f33ede29ee8", ".\\RepositoryImages\\calculatorRanorexSolutionRepository295d527e.rximgres")
        {
            _explorer = new calculatorRanorexSolutionRepositoryFolders.ExplorerAppFolder(this);
            _search = new calculatorRanorexSolutionRepositoryFolders.SearchAppFolder(this);
            _calculator = new calculatorRanorexSolutionRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("295d527e-382c-40e3-bbc6-8f33ede29ee8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("77ec51a1-e710-4f97-a968-ddb70359e798")]
        public virtual calculatorRanorexSolutionRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Search folder.
        /// </summary>
        [RepositoryFolder("154966da-3a63-40ae-94cb-7f6d4ae15a0b")]
        public virtual calculatorRanorexSolutionRepositoryFolders.SearchAppFolder Search
        {
            get { return _search; }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("c7202574-a8d2-4380-aa92-d3d1bbcc0bf6")]
        public virtual calculatorRanorexSolutionRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class calculatorRanorexSolutionRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("77ec51a1-e710-4f97-a968-ddb70359e798")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@class='Shell_TrayWnd']", parentFolder, 30000, null, true, "77ec51a1-e710-4f97-a968-ddb70359e798", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "?/?/button[@accessiblename='Start']", 30000, null, "27b6d1b7-9ad5-4c16-a459-16be74d5373c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77ec51a1-e710-4f97-a968-ddb70359e798")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77ec51a1-e710-4f97-a968-ddb70359e798")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("27b6d1b7-9ad5-4c16-a459-16be74d5373c")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("27b6d1b7-9ad5-4c16-a459-16be74d5373c")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }
        }

        /// <summary>
        /// The SearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("154966da-3a63-40ae-94cb-7f6d4ae15a0b")]
        public partial class SearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _id161Info;

            /// <summary>
            /// Creates a new Search  folder.
            /// </summary>
            public SearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Search", "/winapp[@packagename='Microsoft.Windows.Cortana']", parentFolder, 30000, null, true, "154966da-3a63-40ae-94cb-7f6d4ae15a0b", "")
            {
                _id161Info = new RepoItemInfo(this, "Id161", ".//list[@automationid='suggestionsList']/listitem[@automationid='id_161']", 30000, null, "2ac256ac-9d21-4239-b6f9-02cf6879b76e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("154966da-3a63-40ae-94cb-7f6d4ae15a0b")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("154966da-3a63-40ae-94cb-7f6d4ae15a0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Id161 item.
            /// </summary>
            [RepositoryItem("2ac256ac-9d21-4239-b6f9-02cf6879b76e")]
            public virtual Ranorex.ListItem Id161
            {
                get
                {
                    return _id161Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Id161 item info.
            /// </summary>
            [RepositoryItemInfo("2ac256ac-9d21-4239-b6f9-02cf6879b76e")]
            public virtual RepoItemInfo Id161Info
            {
                get
                {
                    return _id161Info;
                }
            }
        }

        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7202574-a8d2-4380-aa92-d3d1bbcc0bf6")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1Info;
            RepoItemInfo _num1buttonInfo;
            RepoItemInfo _text0Info;
            RepoItemInfo _num0buttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "c7202574-a8d2-4380-aa92-d3d1bbcc0bf6", "")
            {
                _text1Info = new RepoItemInfo(this, "Text1", "?/?/button[@automationid='num1Button']/text[@name='1']", 30000, null, "86cd5636-179d-41a6-93df-279224d78a8a");
                _num1buttonInfo = new RepoItemInfo(this, "Num1Button", "?/?/button[@automationid='num1Button']", 30000, null, "21ea6c49-389b-4364-a187-848b4d189f8c");
                _text0Info = new RepoItemInfo(this, "Text0", "?/?/button[@automationid='num0Button']/text[@name='0']", 30000, null, "9df62ee2-47ec-4407-8d84-2a80b00a0564");
                _num0buttonInfo = new RepoItemInfo(this, "Num0Button", "?/?/button[@automationid='num0Button']", 30000, null, "bb49ebf4-1b48-4df5-8dd7-1392ed4dd520");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7202574-a8d2-4380-aa92-d3d1bbcc0bf6")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7202574-a8d2-4380-aa92-d3d1bbcc0bf6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("86cd5636-179d-41a6-93df-279224d78a8a")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("86cd5636-179d-41a6-93df-279224d78a8a")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Num1Button item.
            /// </summary>
            [RepositoryItem("21ea6c49-389b-4364-a187-848b4d189f8c")]
            public virtual Ranorex.Button Num1Button
            {
                get
                {
                    return _num1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num1Button item info.
            /// </summary>
            [RepositoryItemInfo("21ea6c49-389b-4364-a187-848b4d189f8c")]
            public virtual RepoItemInfo Num1ButtonInfo
            {
                get
                {
                    return _num1buttonInfo;
                }
            }

            /// <summary>
            /// The Text0 item.
            /// </summary>
            [RepositoryItem("9df62ee2-47ec-4407-8d84-2a80b00a0564")]
            public virtual Ranorex.Text Text0
            {
                get
                {
                    return _text0Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text0 item info.
            /// </summary>
            [RepositoryItemInfo("9df62ee2-47ec-4407-8d84-2a80b00a0564")]
            public virtual RepoItemInfo Text0Info
            {
                get
                {
                    return _text0Info;
                }
            }

            /// <summary>
            /// The Num0Button item.
            /// </summary>
            [RepositoryItem("bb49ebf4-1b48-4df5-8dd7-1392ed4dd520")]
            public virtual Ranorex.Button Num0Button
            {
                get
                {
                    return _num0buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num0Button item info.
            /// </summary>
            [RepositoryItemInfo("bb49ebf4-1b48-4df5-8dd7-1392ed4dd520")]
            public virtual RepoItemInfo Num0ButtonInfo
            {
                get
                {
                    return _num0buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}